# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='room',
            field=models.ManyToManyField(to='account.Room'),
        ),
    ]
