# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='introduction',
            field=models.TextField(default='About me.', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(choices=[('NTU', 'National Taiwan University'), ('NTNU', 'National Taiwan Normal University'), ('NTUST', 'National Taiwan University of Science and Technology')], default='NTUST', max_length=5),
        ),
    ]
