# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180609_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='room',
            field=models.ManyToManyField(blank=True, to='account.Room'),
        ),
    ]
