# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_commodity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='img',
            field=models.ImageField(default='/images/9.png', upload_to='images'),
        ),
    ]
