# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_commodity_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
