# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20180521_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='introduction',
            field=models.TextField(max_length=300),
        ),
    ]
