# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20180524_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='type',
            field=models.CharField(choices=[('CP', 'computer_phone_electronics'), ('FN', 'furniture'), ('TR', 'transpotation'), ('TF', 'toy_figure_videogame_'), ('HB', 'habitat'), ('CL', 'clothes'), ('AC', 'accessory'), ('FD', 'food'), ('CS', 'custom'), ('BK', 'book'), ('MM', 'music_movie_culture'), ('HS', 'house'), ('SP', 'sport'), ('OT', 'other')], default='CP', max_length=2),
        ),
    ]
