# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20180608_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='type',
            field=models.CharField(choices=[('CP', '電腦 , 手機 , 電子周邊'), ('FN', '家電 , 家具'), ('TR', '交通工具'), ('TF', '玩具 , 公仔 , 電玩'), ('HB', '生活居家'), ('CL', '服飾'), ('AC', '飾品 , 配件'), ('FD', '食品'), ('CS', '保養 , 彩妝'), ('BK', '書籍'), ('MM', '音樂 , 電影 , 文創'), ('HS', '租屋'), ('SP', '運動'), ('OT', '其他')], default='CP', max_length=2),
        ),
    ]
