# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180528_1136'),
        ('post', '0010_auto_20180609_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='ranker',
            field=models.ManyToManyField(to='account.Profile'),
        ),
    ]
