# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_post_ranker'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rank_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
