# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 05:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_post_rank_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ranker',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
