# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20180610_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ranker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='rank',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rank_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ranker',
        ),
        migrations.DeleteModel(
            name='rank',
        ),
        migrations.AddField(
            model_name='post',
            name='Ranker',
            field=models.ManyToManyField(blank=True, to='post.ranker'),
        ),
    ]
